import type { Metadata } from "next";
import Navbar from "./components/layout/navbar";
import "./globals.css";
import Footer from "./components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen flex flex-col justify-center items-center">
        <div className="w-screen lg:w-[80vw]">
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
